config_version = "0"

[plugins.releases.trivy]
github = "aquasecurity/trivy"
download_type = "targz"
strip_components = 0

[plugins.definitions.trivy]
releases = ["trivy"]
config_files = ["trivy.yaml", "trivy-secret.yaml"]
suggested = "targets"
latest_version = "0.50.1"
known_good_version = "0.50.1"
version_command = "trivy --version"

[plugins.definitions.trivy.drivers.fs-vuln]
# Defining file_types at driver level since each works with different files
file_types = ["lockfile"]
script = "trivy fs ${target} --scanners vuln --format sarif --no-progress"
success_codes = [0]
output = "stdout"
output_format = "trivy_sarif"
cache_results = true
batch = false
description = "Comprehensive and versatile security scanner"
security = true
idempotent = false

[plugins.definitions.trivy.drivers.fs-secret]
# Defining file_types at driver level since each works with different files
file_types = ["ALL"]
script = "trivy fs ${target} --scanners secret --format sarif --no-progress"
success_codes = [0]
output = "stdout"
output_format = "trivy_sarif"
cache_results = true
batch = false

[plugins.definitions.trivy.drivers.config]
# Defining file_types at driver level since each works with different files
file_types = ["docker", "yaml", "terraform"]
script = "trivy config ${target} --format sarif"
success_codes = [0]
output = "stdout"
output_format = "trivy_sarif"
cache_results = true
batch = false
