config_version = "0"

[plugins.releases.shellcheck]
github = "koalaman/shellcheck"
download_type = "tarxz"
strip_components = 1

[plugins.definitions.shellcheck]
releases = ["shellcheck"]
file_types = ["shell"]
config_files = [".shellcheckrc", "shellcheckrc"]
version_command = "shellcheck --version"
recommended = true
issue_url_format = "https://github.com/koalaman/shellcheck/wiki/${}"

[plugins.definitions.shellcheck.drivers.lint]
script = "shellcheck -f json ${target}"
success_codes = [0, 1]
error_codes = [2, 3, 4]
output = "stdout"
output_format = "shellcheck"
cache_results = true
