config_version = 1

[plugins.downloads.shellcheck]
url = "https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.linux.x86_64.tar.xz"
file_type = "TarXz"

[plugins.definitions.shellcheck]
runtime = "linux"
downloads = ["shellcheck"]
file_types = ["shell"]
config_files = [".shellcheckrc", "shellcheckrc"]
version_command = "shellcheck --version"
recommended = true

[plugins.definitions.shellcheck.drivers.lint]
script = "shellcheck -f json ${target}"
success_codes = [0, 1]
error_codes = [2, 3, 4]
output = "stdout"
output_format = "shellcheck"
cache_results = true
