config_version = "0"

[plugins.downloads.shellcheck]
download_type = "tarxz"

[[plugins.downloads.shellcheck.system]]
cpu = "x86_64"
url = "https://github.com/koalaman/shellcheck/releases/download/v${version}/shellcheck-v${version}.linux.x86_64.tar.xz"

[[plugins.downloads.shellcheck.system]]
cpu = "aarch64"
url = "https://github.com/koalaman/shellcheck/releases/download/v${version}/shellcheck-v${version}.linux.aarch64.tar.xz"

[plugins.definitions.shellcheck]
runtime = "linux"
downloads = ["shellcheck"]
file_types = ["shell"]
config_files = [".shellcheckrc", "shellcheckrc"]
version_command = "shellcheck --version"
recommended = true

[plugins.definitions.shellcheck.drivers.lint]
script = "shellcheck -f json ${target}"
success_codes = [0, 1]
error_codes = [2, 3, 4]
output = "stdout"
output_format = "shellcheck"
cache_results = true
