config_version = "0"

[plugins.releases.osv-scanner]
github = "google/osv-scanner"
download_type = "executable"
strip_components = 0

[plugins.definitions.osv-scanner]
releases = ["osv-scanner"]
config_files = ["osv-scanner.toml"]
version_command = "osv-scanner --version"
issue_url_format = "https://osv.dev/${rule}"

[plugins.definitions.osv-scanner.drivers.lint]
file_types = ["osv-scanner-lockfiles"]
script = "osv-scanner --lockfile=${target} --format sarif"
success_codes = [0, 1, 128]
output = "stdout"
output_format = "sarif"
cache_results = true
batch = false
