config_version = 1

[plugins.definitions.flake8]
runtime = "python"
package = "flake8"
file_types = ["python"]
config_files = [".flake8"]
version_command = "flake8 --version"
recommended = true

[plugins.definitions.flake8.drivers.lint]
script = "flake8 ${target} --output-file \"${tmpfile}\" --exit-zero"
success_codes = [0]
output = "tmpfile"
output_format = "regex"
output_regex = "((?P<path>.*):(?P<line>-?\\d+):(?P<col>-?\\d+): (?P<code>\\S+) (?P<message>.+))\n"
cache_results = true
batch = true
# run_linter_from: parent_directory
#   affects_cache:
#     - setup.cfg
#     - tox.ini
