config_version = "0"

[plugins.releases.tflint]
github = "terraform-linters/tflint"
download_type = "zip"
strip_components = 0

[plugins.definitions.tflint]
releases = ["tflint"]
config_files = [".tflint.hcl"]
suggested = "targets"
file_types = ["terraform"]
latest_version = "0.51.1"
known_good_version = "0.51.1"
version_command = "tflint --version"
description = "A pluggable Terraform linter"

[plugins.definitions.tflint.drivers.lint]
script = "tflint --format=sarif --force"
prepare_script = "tflint --init"
success_codes = [0, 1, 2]
output = "stdout"
output_format = "sarif"
target = { type = "parent" }
runs_from = "target_directory"
