config_version = "0"

[plugins.definitions.sqlfluff]
package = "sqlfluff"
runtime = "python"
file_types = ["sql", "sql-j2", "dml", "ddl"]
version_command = "sqlfluff --version"
config_files = [".sqlfluff"]
recommended = false

[plugins.definitions.sqlfluff.drivers.lint]
script = "sqlfluff lint ${target} --format json --nofail --dialect ansi"
success_codes = [0]
output = "stdout"
output_format = "sqlfluff"
batch = true
