config_version = "0"

[plugins.definitions.clippy]
runtime = "rust"
package = "clippy"
file_types = ["rust"]
suggested = "targets"
latest_version = "0.1.76"
known_good_version = "0.1.76"
version_command = "cargo clippy --version"
config_files = ["clippy.toml", ".clippy.toml"]
affects_cache = ["Cargo.toml", "Cargo.lock"]

[plugins.definitions.clippy.drivers.lint]
script = "cargo clippy --message-format json --locked -- --cap-lints=warn --no-deps"
target = "${parent_with(Cargo.toml)}"
runs_from = "${target_directory}"
success_codes = [0, 101, 383]
output = "stdout"
output_format = "clippy"
batch = true
cache_results = true
