config_version = "0"

[plugins.definitions.semgrep]
runtime = "python"
package = "semgrep"
file_types = ["ALL"]
config_files = [".semgrep.yaml", ".semgrepignore", ".semgrep"]
latest_version = "1.68.0"
known_good_version = "1.40.0"
version_command = "semgrep --version"
description = "Static analysis tool for searching code, finding bugs, and enforcing code standards"

[plugins.definitions.semgrep.drivers.lint]
script = "semgrep --metrics=off --disable-version-check --config .semgrep.yaml --sarif --output=${tmpfile} ${target}"
success_codes = [0]
output = "tmpfile"
output_format = "sarif"
cache_results = true
batch = true
suggested = "config"
