config_version = "0"

[plugins.releases.dotenv-linter]
github = "dotenv-linter/dotenv-linter"
download_type = "targz"
strip_components = 0

[plugins.definitions.dotenv-linter]
releases = ["dotenv-linter"]
latest_version = "3.3.0"
known_good_version = "3.3.0"
version_command = "dotenv-linter --version"

# [plugins.definitions.dotenv-linter.drivers.lint]
# file_types = ["dotenv"]
# script = "dotenv-linter --quiet ${target}"
# success_codes = [0,1]
# output = "stdout"
# output_format = "regex"
# output_regex = "((?P<path>.*):(?P<line>-?\\d+) (?P<code>\\S+): (?P<message>.+))\n"
# cache_results = true
# batch = true

[plugins.definitions.dotenv-linter.drivers.format]
file_types = ["dotenv"]
script = "dotenv-linter fix --quiet ${target}"
success_codes = [0]
output = "rewrite"
cache_results = true
batch = true
driver_type = "formatter"
