config_version = "0"

[plugins.releases.ripgrep]
github = "BurntSushi/ripgrep"
download_type = "targz"
strip_components = 1

[plugins.definitions.ripgrep]
releases = ["ripgrep"]
file_types = ["ALL"]
suggested = "targets"
latest_version = "14.1.0"
known_good_version = "14.1.0"
version_command = "rg --version"
config_files = [".ripgreprc"]

[plugins.definitions.ripgrep.drivers.lint-fixme]
script = "rg \"NOTE|OPTIMIZE|TODO|HACK|XXX|FIXME|BUG\" ${target} --json --word-regexp --only-matching"
success_codes = [0,1]
output = "stdout"
output_format = "ripgrep"
batch = true
cache_results = true
