config_version = "0"

[plugins.definitions.ruff]
runtime = "python"
package = "ruff"
file_types = ["python"]
latest_version = "0.7.0"
known_good_version = "0.5.3"
version_command = "ruff version"
config_files = ["ruff.toml"]
issue_url_format = "https://docs.astral.sh/ruff/rules/${rule}"
description = "Python code formatter"
suggested = "targets"

[plugins.definitions.ruff.drivers.format]
script = "ruff check --exit-zero --output-format sarif --output-file ${tmpfile} ${target}"
success_codes = [0]
output = "tmpfile"
output_format = "sarif"
batch = true
suggested = "targets"
