config_version = "0"

[plugins.definitions.ruff]
runtime = "python"
package = "ruff"
file_types = ["python"]
version_command = "ruff version"
config_files = ["ruff.toml"]
recommended = false
issue_url_format = "https://docs.astral.sh/ruff/rules/${}"

[plugins.definitions.ruff.drivers.format]
script = "ruff check --exit-zero --output-format sarif --output-file \"${tmpfile}\"  ${target}"
success_codes = [0]
output = "tmpfile"
output_format = "sarif"
batch = true
