config_version = "0"

[plugins.definitions.checkov]
runtime = "python"
package = "checkov"
file_types = ["docker", "terraform", "yaml", "json"]
version_command = "checkov --version"
recommended = false
config_files = [".checkov.yml", ".checkov.yaml"]

[plugins.definitions.checkov.drivers.format]
# The coma after ${tmpfile} is absolutely necessary
script = "checkov --output sarif --output-file-path ${tmpfile}, --soft-fail --quiet --compact --file ${target}"
success_codes = [0]
output = "tmpfile"
output_format = "sarif"
batch = false
