# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - name: Install qlty CLI
      env:
        GITHUB_TOKEN: ${{ secrets.QLTY_RELEASES_GITHUB_TOKEN }}
      run:
        cd /tmp &&
        gh --repo qltyai/qlty release download --pattern qlty-x86_64-unknown-linux-gnu.tar.xz &&
        tar -xf qlty-x86_64-unknown-linux-gnu.tar.xz &&
        mv qlty-x86_64-unknown-linux-gnu/qlty /usr/local/bin &&
        qlty --version
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test